[package]
name = "fltk-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1.3.23" }
take_mut = { version = "0.2.2", default-features = false }
