[package]
name = "qmetaobject-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qmetaobject = { version = "0.2.7" }
cstr = { version = "0.2.11" }
